### ISSUE TITLE
Startet neu mit FW 2.31.25 => Verständnisfrage

### ISSUE THREAD

**Issue by Fiiti** [homematic-community/hm-watchdog#15]
Hatte heute von 2.27.8 auf 2.31.25 CCU2 geupdatet.
CCU2 kam quasi nicht hoch, weil das System immer neu startete. Ich vermute hier den watchdog.

Ich habe mir beholfen, indem ich ein Recovery mit der gleichen FW 2.31.25 machte.
Dann war es besser, jedoch ab und wann startete das System doch wieder neu.

Ich konnte aber immerhin den Watchdog auf 60minuten stellen. Nun startet er tatsächlich die ccu alle 60minuten neu.
Ist das so im Sinne des Erfinders? Was stelle ich nun wirklich ein in den watchdog-konfigs?
Ich dachte nur die Zeit der Überprüfung und wenn dann ein Fehler vorliegt, dann restart.

Vermutlich kommt watchdog mit irgendwas nicht klar und startet deswegen neu.

**Comment by jens-maus** [comment]
Momentan wird hm-watchdog von nueren firmware versionen (> 2.78.x) nicht unterstützt und sollte deinstalliert werden.

**Comment by Fiiti** [comment]
Alles klar. Schade. Dennoch danke für Deine tollen Tools!!
