### ISSUE TITLE
Dienst ssdpd und Firmware 2.31.25.20180625

### ISSUE THREAD

**Issue by Andreas0211** [homematic-community/hm-watchdog#17]
Seit gestern habe ich die aktuelle Raspberrymatic 2.31.25.20180625 am Laufen und bekomme seitdem über das Addon Watchdog nach dreißig Minuten Laufzeit der Raspberrymatic den ersten Fehler vom ssdpd Dienst mit dem Hinweis, dass dieser Dienst neu gestartet wurde. Drei Minuten später den 2. Fehler, und weitrere 3 Minuten später dann Fehler Nr. 3. Nach weiteren 3 Minuten wird die Raspberrymatic dann neu gestartet und der Timer beginnt von neuem zu laufen. Nach 30 Minuten geht es dann wieder los. Über Nacht 34 Benachrichtigungs-Emails in meinem Postfach :-( Gibt es hier bereits Abhilfe?

Danke und Gruß
Andreas

**Comment by FraatGIT** [comment]
Ich habe das gleiche Problem.

LG Fraat

**Comment by jens-maus** [comment]
Das ist ein Bug in RaspberryMatic und nicht in Watchdog. Der Bug wurde aber bereits für die nächste RM Version repariert. Bis dahin einfach den Watchdog deaktivieren.

**Comment by Andreas0211** [comment]
Danke für die Antwort! Gibt es denn Bedenken bzgl. der Systemstabilität mit diesem Bug? Ich Track seitdem die Temperatur der Raspberry-CPU, und diese kommt mir mit konstant 56-58°C etwas hoch vor...

**Comment by jens-maus** [comment]
Nein, der hat darauf keinen Einfluss
