### ISSUE TITLE
Auch für aktuelle FW > 3.45.5.x geeignet?

### ISSUE THREAD

**Issue by Fiiti** [homematic-community/hm-watchdog#20]
Hi,
hm_wd 0.8 ist installiert. 
Habe in den letzzten 4 Wochwen 2x den Fall gehabt, dass mein Raspimatic nicht einmal mehr per ssh sich verbinden konnte. Die CCU starb dabei anscheinend nach und nach. Viel nur auf, dass meine 19Tasten HM Fernbedienung mir langsam aber sicher immer mehr Fehler anzeigte.

Ich habe keinerlei "Sonderspiele" drauf - alles schon brav Standard.

Ich muss dann den Raspi stromlos machen, meist dann auch 2x neu starten.

Nun frage ich mich, ob der watrchdog hier nicht hätte anspringen sollen.
Daher die Frage, ob es in der aktuelen FW überhaupt unterstützt wird?

Gruß,
Fi

**Comment by jens-maus** [comment]
Nein, dieses watchdog addon sollte mit der 3.45.5 version nicht mehr verwendet werden. Das wurde sonauch im RaspberryMatic Changelog übrigens erwähnt!
