### ISSUE TITLE
CCU3 von EQ3

### ISSUE THREAD

**Issue by hannoverRed** [homematic-community/hm-watchdog#24]
Hallo,

ich wollte einmal fragen ob ich jetzt das hm-watchdog noch auf der CCU3 von EQ3 installieren kann?
oder ist es schon standardmäßig von EQ3 mitgeliefert?
lg Jörn

**Comment by hannoverRed** [comment]
Kann mir hierzu wer weiterhelfen?

**Comment by jens-maus** [comment]
Das ist hier zwar ein Bug/Issue Tracker und kein Support-Forum, aber die Antwort ist nein, das ist nicht und wird auch so wie das Addon hier funktioniert auch nie von eQ3 direkt in die CCU3 integriert werden.

**Comment by hannoverRed** [comment]
Hallo Jens,

Danke für die Rückmeldung!
Sagt mir jetzt aber grade nicht ob ich dies addon aktiv auf der CCU3 nutzen kann?
Lg
