### ISSUE TITLE
RF-LAN Gateway

### ISSUE THREAD

**Issue by FraatGIT** [homematic-community/hm-watchdog#3]
Hallo,

ich habe merere RF-LAN Gateway an einer CCU 2. Gelegentlich werden Sie nach einem Reboot der CCU nicht verbunden. Es wäre schön wenn man mit dem watchdog auch die RF-LAN Gateway überwachen könnte.

Fraat

**Comment by jens-maus** [comment]
Der Watchdog ansich überwacht nur die jeweiligen Prozesse auf der CCU und prüft ob diese noch laufen und startet sie ggf. neu. Er überprüft jedoch nicht (und wird dies vmtl auch nie) deren Funktionsweisen oder gar ob verbindungen zu angebundenen Geräten funktionieren.

In der aktuellen Version überwacht der watchdog einfach den 'rfd' daemon der auch für die kommunikation mit den RF LAN Gateways verantwortlich ist. Wenn der watchdog also keine probleme erkennt liegt das daran das der rfd daemon wohl läuft auf der CCU. Warum er allerdings keine verbindunh zu den gateways hat ist eine andere frage/problem das der watchdog in seiner jetzigen form auch nicht überprüfen kann.
